### ISSUE TITLE
error generating feed

### ISSUE THREAD

**Issue by tjfayaz120** [gnikolovski/commerce_facebook_catalog#2]
Hi I've successfully installed and activated this module (using composer and then activating it on the frontend) however I see this error when browsing to the https://mysite.co.uk/facebook/catalog URL

`PHP Exception InvalidArgumentException: "Property field_image is unknown." at /var/www/virtual/mysite.co.uk/shop/htdocs/core/lib/Drupal/Core/TypedData/TypedDataManager.php line 196'`

Any ideas how I can resolve this please?

**Comment by gnikolovski** [comment]
This module is NOT plug-and-play. The module is working on one of my sites, but it probably won't work on your site without some modification, unless you have exactly the same fields as I have.

Check out the following article: https://gorannikolovski.com/blog/drupal-commerce-and-facebook-product-catalog
